version: "3.9"

services:
    web:
        build: .
        ports:
            - 8000:8000
        # command: "npm run init npm start"
        depends_on: 
            - mongo
    mongo:
        image: mongo
